name: py-sites

services:
  reverse-proxy:
    image: nginx:1.27-alpine
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./reverse-proxy/conf.d:/etc/nginx/conf.d:ro
      - ./reverse-proxy/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - main
      - shop
      - web_primary
    networks:
      - web
      - internal
    restart: unless-stopped

  main:
    build: ./apps/main
    container_name: app_main
    env_file: .env
    environment:
      - DB_NAME=main_db
    expose:
      - "8000"
    networks:
      - internal
    restart: unless-stopped
    command: ["gunicorn","-b","0.0.0.0:8000","-w","2","wsgi:app"]

  shop:
    build: ./apps/shop
    container_name: app_shop
    env_file: .env
    environment:
      - DB_NAME=shop_db
    expose:
      - "8000"
    networks:
      - internal
    restart: unless-stopped
    command: ["gunicorn","-b","0.0.0.0:8000","-w","2","wsgi:app"]

  web_primary:
    build: ./apps/web_primary
    container_name: app_web_primary
    env_file: .env
    environment:
      - DB_NAME=web_primary_db
    expose:
      - "8000"
    networks:
      - internal
    restart: unless-stopped
    command: ["gunicorn","-b","0.0.0.0:8000","-w","2","wsgi:app"]

  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    env_file: .env
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/init:/docker-entrypoint-initdb.d:ro
    networks:
      - internal
    restart: unless-stopped

networks:
  web:
  internal:
